// src/pages/WebFront/WebFront.jsx
import webFront from './WebFront.module.scss'
import { useSearchParams, Link, Outlet } from 'react-router-dom'
import { useEffect, useState } from 'react'
import baseService from '../../axios/baseService'

let selectId = null
const getCurrentMessage = async (mainId) => {
    // 通过id调用查询接口
    let res = await baseService.get('/getKnowledgeCategory?id=' + mainId)
    let titleName = res.data[0].name
    let parentUrl = res.data[0].url
    let sideBarList = []
    // 当前内容列表
    await baseService.get('/modelList?parentId=' + mainId).then((res) => {
        sideBarList = res.data
        sideBarList.forEach(item => {
            item.url = '/' + parentUrl + '/' + item.url + '?mainId=' + mainId + '&branchId=' + item.id
        });
    })
    return { sideBarList, titleName }
}

const goHome = () => {
    window.location.replace('/');
}
const goBack=()=>{
    window.history.go(-1)
}
const selectOption = (id) => {
    return () => {
        selectId = id
    }
}


export default function WebFront() {
    const [titleName, setTitleName] = useState('')
    const [sideBarList, setSideBarList] = useState([])
    const [searchParams] = useSearchParams()
    let mainId = searchParams.get('mainId')

    useEffect(() => {
        getCurrentMessage(mainId).then((res) => {
            setSideBarList(res.sideBarList)
            setTitleName(res.titleName)
        })
    }, [mainId])

    return (
        <div>
            <div className={webFront.user_bar}>
                <span onClick={goHome} style={{ textDecoration: 'none', color: '#335f5b', marginLeft: '20px', float: 'left' }}>
                    回到首页
                </span>
                <span onClick={goBack} style={{ textDecoration: 'none', color: '#335f5b', marginRight: '20px', float: 'right' }}>
                    返回
                </span>

                <div style={{ textAlign: 'center' }}>
                    <span style={{ fontSize: '30px', fontWeight: 'bolder', color: '#2C3E50' }}>{titleName}</span>
                </div>
            </div>

            <div className={webFront.content}>
                <div className={webFront.option_bar}>
                    <ul>
                        {
                            sideBarList.map((item) => {
                                return (
                                    <li key={item.id} onClick={selectOption(item.id)} className={selectId==item.id ? webFront.select_option : ''} >
                                        <Link className={webFront.bg} to={item.url}>{item.name}</Link>
                                    </li>
                                )
                            })
                        }
                    </ul>
                </div>
                <div id="test" className={webFront.box_1}>
                    {
                        selectId == null ?
                            (<div style={{ textAlign: 'left', fontSize: '20px', padding: '10px' }}>请选择~~~</div>) :
                            (<div><Outlet /></div>)
                    }

                </div>
            </div>

        </div>
    )
}

// src/views/web-front/WebFront.vue
<template>

    <div class="">
        <div class="user_bar">
            <a @click="goHome()" style="text-decoration: none;color:#335f5b;margin-left: 20px;float: left;">
                回到首页
            </a>

            <a @click="goBack()" style="text-decoration: none;color:#335f5b;margin-right: 20px;float: right;">
                返回
            </a>            
            <div><a style="font-size:30px;font-weight: bolder;">{{titleName}}</a></div>
        </div>

        <div class="content">
            <div class="option_bar" :class="{fixed:isFixed}">
                <ul>
                    <li v-for="(item,index) in sideBarList" :class="selectId==item.id ? 'select-option' : '' " @click="selectOption(item.id)">
                        <router-link class="bg" :to="item.url">{{item.name}}</router-link>
                    </li>
                </ul>
            </div>
            
            <div id="test" class="box_1">
                <div v-if="selectId==null" style="text-align: left;font-size: 20px;padding: 10px">请选择~~~</div>
                <div v-else>
                    <router-view></router-view>
                </div>
            </div>
        </div>
      
    </div>
</template>



<script lang="ts" setup>
import {onMounted,onActivated,ref,reactive,watch,created} from 'vue';
import {useRouter,useRoute} from 'vue-router';
import baseService from "../../axios/baseService"


//向前推进路由的
const router = useRouter()
//获取路由参数的
const route = useRoute()
const titleName = ref('')
const sideBarList = reactive([])

//选择的模块
const selectId = ref()

const goBack=()=>{
    router.go(-1)
}

const goHome=()=>{
    // 以下内容不会刷新页面————所以对于webFron来说，从那里跳转到这里还是onMountedh状态里面
    // router.push("/")
    window.location.replace('/');

}

const isFixed = ref(false)

const selectOption = (id)=>{
    selectId.value =id
}

onMounted(()=>{
    // 通过id调用查询接口
    let parentUrl = ''
    let mainId = route.query.mainId

    // 上级路由
    baseService.get('/getKnowledgeCategory?id='+mainId).then(async(res)=>{
        titleName.value = res.data[0].name
        parentUrl = res.data[0].url

        // 当前内容列表
        await baseService.get('/modelList?parentId='+mainId).then((res)=>{
            let list  = res.data
            list.forEach(item => {
                item.url = '/'+parentUrl+'/'+item.url+'?mainId='+mainId+'&branchId='+item.id
            });
            Object.assign(sideBarList,list)  
        })
      
    })   
})




</script>



<style lang="scss" scoped>

@import "../../assets/css/vue.scss";

.user_bar{
    width:100%;
    height:$userBarHeight;
    background-color:#D9B2B1;
    line-height: $userBarHeight;
}


.content{
    position: relative;
    display: flex;
    flex-direction: row;

    width:100%;
    min-height: calc(100vh - $topBarHeight - $footerHeight - $userBarHeight);
    background-color:white;
    
    .option_bar{
        width: 15%;
        overflow-y: auto;
        min-height: calc(100vh - $topBarHeight - $footerHeight - $userBarHeight);
        background-color:#FBEDF7;

        &>ul{
            margin-top: 10%;

            
            .select-option{
                background-color: pink;
            }

            &>li{
                display: flex;
                flex-direction:column;
                justify-content:center;
                height: $sideBarItemHeight;
                a{
                    cursor:pointer
                }
            }
        }
    }
        
    .box_1{
        width: 85%;
        position: relative;
    }

}

</style>
