// src/pages/WebFront/Base/Js/Js.jsx
import {useSearchParams,Link} from 'react-router-dom'
import {useEffect,useState,} from 'react'
import baseService from '../../../../axios/baseService'
import js from './Js.module.scss'

const getCurrentMessage = async (mainId,branchId,branchRightId) => {
    let list = []
    let modelTitle = ''
 
    // 获取上级路由信息
    await baseService.get('/modelBranchList?id='+branchRightId).then(async(res)=>{
        modelTitle = res.data[0].name
        //获取当前路由信息    
       await baseService.get('/contentList?parentId='+branchRightId).then((res)=>{
            list = res.data
            list.forEach(item => {
                item.url = item.url + '?mainId='+mainId+'&branchId='+branchId+'&branchRightId='+branchRightId+'&id='+ item.id          
            });
        })
    })
    return {list,modelTitle}
}

export default function Js(){
    const [searchParams] = useSearchParams()
    const [modelTitle,setModelTitle] = useState('')
    const [contentList,setContentList] = useState([])
    let mainId = searchParams.get('mainId')
    let branchId  = searchParams.get('branchId')
    let branchRightId  = searchParams.get('branchRightId')

    useEffect(()=>{
        getCurrentMessage(mainId,branchId,branchRightId).then((res)=>{
            setModelTitle(res.modelTitle)
            setContentList(res.list)
        })
    },[mainId,branchId,branchRightId])

    return (
        <div className={js.js}>
            <div className={js.title}>{modelTitle}</div>
            {contentList.length > 0 && (
                    <ul>
                        {contentList.map((item,index)=>{
                            return(
                                <li key={item.id}>
                                    <Link to={item.url}>{(index+1)+'. '+item.name}</Link>
                                </li>
                            )
                        })}
                    </ul> 
            )}
        </div>
    )
}

// src/views/web-front/base/JS/Js.vue
<template>
    <div>
        <div class="title">{{modelTitle}}</div>
        <div>
            <ul>
                <li v-for="(item,index) in contentList">
                    <router-link :to="item.url">{{(index+1)+'. '+item.name}}</router-link>
                </li>              
            </ul>                  
        </div>
    </div>
</template>

<script lang="ts" setup>
import baseService from "../../../../axios/baseService"
import {ref, onMounted,reactive} from 'vue'
import dayjs from 'dayjs'
import {ElMessage} from 'element-plus'

import {useRoute} from 'vue-router'
const route = useRoute()

const contentList = reactive([])
const modelTitle = ref('')

onMounted(()=>{
  
    let parentUrl = ''
    let mainId = route.query.mainId
    let branchId = route.query.branchId
    let branchRightId = route.query.branchRightId


    // 获取上级路由信息
    baseService.get('/modelBranchList?id='+branchRightId).then(async(res)=>{
        parentUrl = res.data[0].url
        modelTitle.value = res.data[0].name
        
        //获取当前路由信息    
        baseService.get('/contentList?parentId='+branchRightId).then((res)=>{
        
            let list = res.data
            list.forEach(item => {
                item.url = parentUrl + '/'+ item.url + '?mainId='+mainId+'&branchId='+branchId+'&branchRightId='+branchRightId+'&id='+ item.id          
            });

            Object.assign(contentList,list)

        })

    })

})



</script>


<style scoped>
    ul{
        text-align: left;
        margin-left: 10px;
    }

    ul>li{
        background-color: snow;
        margin:5px;

    }

    .title{
        font-size: 20px;
        padding: 5px 0;
        background-color: rgb(233, 207, 245);
    }

  

    
</style>
