// src/pages/WebFront/Base/Js/JsContent/JsContent.jsx
import baseService from "../../../../../axios/baseService"
import {useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import jsContent from  './JsContent.module.scss'

const getCurrentMessage = async(id) => {
    let title = ''
    let detailContent = ''
    // 通过id查找对应的内容
    await baseService.get('/content?id='+id).then((res)=>{
        detailContent = res.data.content
    })
    // 通过id查找name
    await baseService.get('/contentList?id='+id).then((res)=>{
        title = res.data[0].name
    })
    return {detailContent,title}
}

export default function JsContent(){
    const [searchParams] = useSearchParams()
    const [title,setTitle] = useState('')
    const [detailContent,setDetailContent] = useState('')
    let id = searchParams.get('id')
    useEffect(()=>{
        getCurrentMessage(id).then((res)=>{
            setTitle(res.title)
            setDetailContent(res.detailContent)
        })
    },[id])

    return(
        <div>
            <div><h3>{title}</h3></div>
            <div dangerouslySetInnerHTML={{__html:detailContent}} className={jsContent.content}>
            </div>
        </div>
    )
}

// src/views/web-front/base/JS/JsContent.vue
<template>

    <div >
        <div><h3>{{title}}</h3></div>
        <div class="content" v-html="detailContent"></div>
    </div>
</template>


<script lang="ts" setup>
import {onMounted,ref} from 'vue'
import {useRoute} from 'vue-router'
import baseService from "../../../../axios/baseService"

// 用来格式化页面上的code文本
import Prism from "../../../../assets/markdown/prism.js"
import "../../../../assets/markdown/prism.css"

const route = useRoute()
const detailContent = ref('')
const title = ref('')

onMounted(()=>{
    // 通过id查找对应的内容
    baseService.get('/content?id='+route.query.id).then((res)=>{
        // console.log('res=====',res)
        detailContent.value = res.data.content
    })

    // 通过id查找name
    baseService.get('/contentList?id='+route.query.id).then((res)=>{
        console.log('res==+++++===',res.data[0].name)

        title.value = res.data[0].name
        // detailContent.value = res.data.content
    })

})



</script>

<style scoped>
    .content{
        padding: 10px 10px;

    }
</style>
